name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@v1.1.1    
        with:
          args: --insecure https://jacate.70533df3.shooteram.fr:8000 --data '${{toJSON(github)}}' -H "Authorization:\ ${{secrets.AUTHORIZATION}}" -H "Content-Type:\ application/json"
